name: Assign On-Call Analyst

on:
  issues:
    types: [labeled]

jobs:
  assign-on-call-analyst:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.label.name == 'admin-fin-sys-bot'
    steps:
      - name: Assign Issue
        uses: actions-cool/issues-helper@v3.6.0
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: @finsys-error-bot
      - name: Tell Me Who's On Call
        run: echo "${{ vars.FINANCIAL_SYSTEMS_ON_CALL_ANALYST }} is on call!" 
