name: Assign On-Call Analyst

on:
  issues:
    types: [labeled]

jobs:
  assign-on-call-analyst:
    runs-on: ubuntu-latest
#    env:
#      FINANCIAL_SYSTEMS_ON_CALL_ANALYST: ${{ vars.FINANCIAL_SYSTEMS_ON_CALL_ANALYST }}
    permissions:
      issues: write
    if: github.event.label.name == 'admin-fin-sys-bot'
    steps:
      - name: Assign Issue
        uses: actions-cool/issues-helper@v3.6.0
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ vars.FINANCIAL_SYSTEMS_ON_CALL_ANALYST }}
